[package]
name = "lite"
version = "0.1.0"
edition = "2018"

[dependencies]
env_logger = "0.9.0"
npc = { path = "./npc" }
rustyline = "9.0.0"
rustyline-derive = "0.5.0"

[dev-dependencies]
pretty_assertions = "1.0.0"

[workspace]
members = ["./npc"]

